# .NET 转前端基础知识笔记

外部函数调用之后其变量对象本应该被销毁，但闭包的存在使我们仍然可以访问外部函数的变量对象。  

本质上来说函数调用以后变量被GC回收了，我们通过一种方法可以让这个变量不要被回收，这就是闭包。  

创建闭包最常见方式，就是在一个函数内部创建另一个函数。  
看一个最简单的例子我们声明一个test，这个test其实是一个函数，两次text(0)打印出来发现是2和3  
也就是说这个a一直在内存中没有被回收`var test = test(1);`时候我们给赋值为1，第一次text(0)a自增为2，第二次自增为3。
```javascript
        function test(a) {
            return function(b) {
                console.log(++a + b);
            }
        }

        var test = test(1);
        test(0);
        test(0);
```


再看一个例子，分析打印结果：
```javascript
   function fun(n, l) {
            console.log(l);
            return {
                fun: function(m) {
                    return fun(m, n);
                }
            }
        }       

        var a = fun(0);  //打印undefined
        a.fun(1);  //0
        a.fun(2);  //0
        a.fun(3);  //0

        //  undefined    0      1     2
        var b = fun(0).fun(1).fun(2).fun(3);

        //     undefined    0 
        var c = fun(0).fun(1);
        // 1
        c.fun(2);
        // 1
        c.fun(3);
```
其实这个例子我们只要把握住一点，就是这个n，观察fun这个函数我们发现只有n这个参数是在内部的函数中用过的，所以只有它形成了闭包。  
当我们执行一次fun()时发生了什么？    

首先看a声明一个a调用了fun(0);这时候会n=0 l=undefined  打印出undefined。这时候a是一个函数function(m) { return fun(m, 0); }
这里注意一下其实这个n是有值的为0。这时候调用a.fun(1)其实就是在执行fun(1, 0)，打印出来第二个参数0。
所以说无论a.fun(x)这个值传什么打印出来都会是0，因为这个a中的n始终是0。

看c，首先fun(0)打印undefined返回一个function(m) { return fun(m, 0); },这时候fun(1)打印一个0返回一个function(m) { return fun(m, 1); }这时候c就是function(m) { return fun(m, 1)。
这时候就跟a一样了无论c.fun(x)的x传什么打印出来都会是1。

b也同理，打印的结果在注释里。





